version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
    - "5432:5432"
    networks:
      - app_network
    container_name: db
    env_file:
      - .env

  web:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - web
    networks:
      - app_network
    env_file:
      - .env

volumes:
  postgres_data:
  frontend:
    name: frontend
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./frontend

networks:
  app_network:
    driver: bridge