version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: pongdb
      POSTGRES_USER: ponguser
      POSTGRES_PASSWORD: pongpassword

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=pongdb
      - DB_USER=ponguser
      - DB_PASSWORD=pongpassword
      - DB_HOST=db
      - DB_PORT=5432

  frontend:
    build: ./frontend
    ports:
      - "3000:443"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - web

volumes:
  postgres_data:
  frontend:
    name: frontend
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./frontend 