# Generated by Django 3.2.25 on 2024-06-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('social_access_token', models.CharField(max_length=100)),
                ('social_refresh_token', models.CharField(max_length=100)),
                ('token_expiration_time', models.DateTimeField()),
                ('lang', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('intra_id', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=100)),
            ],
        ),
    ]
